server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/vehicles
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

spring.kafka:
  bootstrap-servers: kafka:9092

logging:
  level:
    org:
      springframework:
        kafka: DEBUG
        jpa: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
