server:
  port: 8086

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

spring.kafka:
  bootstrap-servers: localhost:9092

logging:
  level:
    org:
      springframework:
        kafka: DEBUG
        jpa: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

openapi:
  dev:
    url: http://localhost:8086