scrape_configs:
  - job_name: 'VehicleApplicationMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8086']
        labels:
          application: 'My Spring Boot Application'